### ISSUE TITLE
The Init Script Fails to Produce an Odbc Connection with DBI::dbConnect to Another Compute (Likely) Starting With 14.3 LTS

### ISSUE THREAD

**Issue by jarek-kupisz** [zacdav-db/databricks-r-env#2]
Hi! I am not sure if the repository is still maintained, but if yes, first thank you for providing this code - it was a lot of help in my case!

My primary use case for the ability to connect to other computes via ODBC is allowing an R Shiny app, that needs to work in no isolation shared cluster policy, to query the lake data. I send queries from the app to our SQL compute via DBI, odbc and dbplyr R packages. This is done not only for the ability to query the data at all but also due to SQL's compute speed. Therefore I really would like for this script to continue working. 

I wanted to migrate my project to DBR15.4 LTS but then the same code that works fine on DBR 12.2 (I have no option to check 13.3 LTS), stops working in an awkward way. The same Simba driver version, the same R packages version. The error I get from dbConnect is: 
```
Error in `Rserve::run.Rserve()`:
! ODBC failed with error 00000 from [Simba][ODBC].
✖  (11560) Unable to locate SQLGetPrivateProfileString function.
ℹ From 'nanodbc/nanodbc.cpp:1150'.
```
I write that it fails in an awkward way because when after executing the init script I do in shell `isql <dsn> token <api token>` and it is able to connect. I spend hours at this point with google and LLMs trying to wrap my head around it but to no avail. 

I think the problem comes down to how linux dependencies are installed. On DBR 12.2 and prior `odbcinst` seems to be correctly installed from the get-go while in the failing DBR versions, it is declared as missing dependency by `apt-get update`.  This makes the `odbcinst -j` fail before execution of the init script and likely translates into problems for R's odbc. Unfortuately I am not a computer scientist by trade so I am completely green in linux packages management. 

The only other thread resembling this issue on the tidyverse side is this one https://github.com/r-dbi/odbc/issues/709, however, as expected from Hadley and co., the issue was patched on their end. I also tested various odbc versions from non-CRAN installations and the issue persists. 

I would be grateful for someone on Databricks side to try to reproduce this problem🙏. 

Jarek

**Comment by zacdav-db** [comment]
Thanks @jarek-kupisz, can you try the changes I just made?

Thanks!

**Comment by jarek-kupisz** [comment]
Hey @zacdav-db , thanks a lot it works now!!!

The missing piece was installing `odbcinst1debian2`, so at least I know what I don't know 😅.

2 small suggestions from my side ( I don't want to do any commits as I am not sure how to reproduce your env):

- you suggest overwriting the `odbc.ini` while in many cases other DSNs might be already available (eg. in my case I also put a MS SQL connection with a script by someone else before my init script)
- you changed from `odbc::odbc()` to `odbc::databricks()` which fails in my case. The latter expects `DATABRICKS_HOST` env variable or a workspace argument, `uid`, `pwd` and `httppath` explicitly provided, as it seems to ignore DSN. `odbc::odbc` works as it used to so I'll stick to it.

Thank you!
Jarek
